DROP DATABASE IF EXISTS mygames;
CREATE DATABASE mygames;
USE mygames;

CREATE TABLE Authors (
    AuthorID INT NOT NULL AUTO_INCREMENT,
    AuthorName VARCHAR(255) NOT NULL,
    PRIMARY KEY (AuthorID)
);

CREATE TABLE Publishers (
    PublisherID INT NOT NULL AUTO_INCREMENT,
    PublisherName VARCHAR(255) NOT NULL,
    PRIMARY KEY (PublisherID)
);

CREATE TABLE Games (
    GameID INT NOT NULL AUTO_INCREMENT,
    GameName VARCHAR(255) NOT NULL,
    AuthorID INT NOT NULL,
    PublisherID INT NOT NULL,
    BoxPrice DECIMAL(10,2) NOT NULL,
    AgeLimit INT NOT NULL,
    DurationMinutes INT NOT NULL,
    SoldUnits INT NOT NULL,
    PRIMARY KEY (GameID),
    FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID),
    FOREIGN KEY (PublisherID) REFERENCES Publishers(PublisherID)
);

CREATE TABLE GameTranslations (
    GameID INT NOT NULL,
    LanguageCode VARCHAR(2) NOT NULL,
    GameName VARCHAR(255) NOT NULL,
    PRIMARY KEY (GameID, LanguageCode),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);
INSERT INTO Authors (AuthorName) VALUES
    ('Reiner Knizia'),
    ('Vlaada Chvátil'),
    ('Stefan Feld'),
    ('Uwe Rosenberg'),
    ('Jamey Stegmaier'),
    ('Eric Lang'),
    ('Elizabeth Hargrave'),
    ('Rob Daviau'),
    ('Matt Leacock'),
    ('Wolfgang Kramer'),
    ('Michael Kiesling'),
    ('Richard Garfield'),
    ('Bruno Cathala'),
    ('Antoine Bauza'),
    ('Phil Walker-Harding'),
    ('Alexander Pfister'),
    ('Leder Games'),
    ('Vital Lacerda'),
    ('Dávid Turczi'),
    ('Isaac Childres'),
    ('Ryan Laukat'),
    ('Splotter Spellen'),
    ('Corey Konieczka'),
    ('Eric M. Lang'),
    ('Prospero Hall'),
    ('Cole Wehrle'),
    ('Neil Gaiman'),
    ('Martin Wallace'),
    ('Ryan Cordell'),
    ('Kevin Wilson'),
    ('Michael Elliott');

INSERT INTO Publishers (PublisherName) VALUES
    ('Kosmos'),
    ('Czech Games Edition'),
    ('Queen Games'),
    ('HABA'),
    ('Stonemaier Games'),
    ('CMON'),
    ('Academy Games'),
    ('Z-Man Games'),
    ('Victory Point Games'),
    ('Mayfair Games'),
    ('Ravensburger'),
    ('Wizards of the Coast'),
    ('Asmodee'),
    ('Matagot'),
    ('Bezier Games'),
    ('Eagle-Gryphon Games'),
    ('Gamewright'),
    ('Repos Production'),
    ('Portal Games'),
    ('Greater Than Games'),
    ('GMT Games'),
    ('Ares Games'),
    ('Jamey Stegmaier Games'),
    ('Kickstarter'),
    ('North Star Games'),
    ('Marvel'),
    ('Ares Games'),
    ('Corvus Belli'),
    ('Renegade Game Studios');

INSERT INTO Games (GameName, AuthorID, PublisherID, BoxPrice, AgeLimit, DurationMinutes, SoldUnits) VALUES
    ('Catan', 1, 1, 50.00, 10, 60, 25000000),
    ('7 Wonders', 2, 3, 50.00, 10, 30, 2000000),
    ('Carcassonne', 1, 4, 30.00, 8, 30, 10000000),
    ('Ticket to Ride', 5, 6, 40.00, 8, 60, 10000000),
    ('Pandemic', 2, 7, 40.00, 10, 60, 5000000),
    ('Agricola', 1, 8, 50.00, 12, 90, 1000000),
    ('Wingspan', 9, 10, 50.00, 10, 40, 1000000),
    ('Root', 11, 12, 60.00, 10, 60, 500000),
    ('Spirit Island', 13, 14, 80.00, 14, 90, 250000),
    ('Gloomhaven', 15, 16, 140.00, 12, 120, 500000),
    ('Twilight Imperium: Fourth Edition', 17, 18, 150.00, 14, 240, 250000),
    ('Mage Knight', 15, 19, 100.00, 12, 120, 500000),
    ('Terraforming Mars', 18, 20, 70.00, 12, 120, 500000),
    ('Le Havre', 1, 8, 50.00, 12, 120, 500000),
    ('Great Western Trail', 19,  8, 50.00, 12, 120, 500000),
    ('Everdell', 11, 21, 60.00, 10, 40, 500000),
    ('Scythe', 22, 23, 70.00, 14, 90, 500000),
    ('Arkham Horror: The Card Game', 24, 25, 60.00, 14, 60, 500000),
    ('Food Chain Magnate', 26, 27, 100.00, 12, 120, 250000),
    ('Concordia', 1, 28, 50.00, 13, 60, 500000),
    ('The Castles of Burgundy', 29, 20, 50.00, 12, 90, 500000),
    ('Puerto Rico', 29, 20, 50.00, 12, 120, 500000),
    ('Terraforming Mars: Ares Expedition', 18, 20, 30.00, 12, 60, 500000),
    ('Wingspan: European Expansion', 9, 10, 30.00, 10, 40, 500000),
    ('Spirit Island: Jagged Earth', 13, 20, 60.00, 14, 120, 250000),
    ('Gloomhaven: Jaws of the Lion', 15, 16, 60.00, 12, 90, 500000),
    ('Codenames: Duet', 20, 20, 20.00, 10, 15, 500000);

INSERT INTO GameTranslations (GameID, LanguageCode, GameName) VALUES
    (1, 'fr', 'Les Colons de Catane'),
    (1, 'es', 'Catan'),
    (2, 'fr', '7 Wonders'),
    (2, 'es', '7 Maravillas'),
    (3, 'fr', 'Carcassonne'),
    (3, 'es', 'Carcassonne'),
    (4, 'fr', 'Ticket to Ride'),
    (4, 'es', 'Trenes por Europa'),
    (5, 'fr', 'Pandémie'),
    (5, 'es', 'Pandemic'),
    (6, 'fr', 'Agricola'),
    (6, 'es', 'Agricola'),
    (7, 'fr', 'Wingspan'),
    (7, 'es', 'Wingspan'),
    (8, 'fr', 'Root'),
    (8, 'es', 'Root'),
    (9, 'fr', 'Île aux Esprits'),
    (9, 'es', 'Spirit Island'),
    (10, 'fr', 'Gloomhaven'),
    (10, 'es', 'Gloomhaven'),
    (11, 'fr', 'Twilight Imperium: Quatrième Édition'),
    (11, 'es', 'Twilight Imperium: Cuarta Edición'),
    (12, 'fr', 'Mage Knight'),
    (12, 'es', 'Mage Knight'),
    (13, 'fr', 'Terraforming Mars'),
    (13, 'es', 'Terraforming Mars'),
    (14, 'fr', 'Le Havre'),
    (14, 'es', 'El Havre'),
    (15, 'fr', 'Great Western Trail'),
    (15, 'es', 'Great Western Trail'),
    (16, 'fr', 'Everdell'),
    (16, 'es', 'Everdell'),
    (17, 'fr', 'Scythe'),
    (17, 'es', 'Scythe'),
    (18, 'fr', 'Arkham Horror: Le Jeu de Cartes'),
    (18, 'es', 'Arkham Horror: El Juego de Cartas'),
    (19, 'fr', 'Food Chain Magnate'),
    (19, 'es', 'Food Chain Magnate'),
    (20, 'fr', 'Concordia'),
    (20, 'es', 'Concordia'),
    (21, 'fr', 'Les Châteaux de Bourgogne'),
    (21, 'es', 'Los Castillos de Borgoña'),
    (22, 'fr', 'Puerto Rico'),
    (22, 'es', 'Puerto Rico'),
    (23, 'fr', 'Terraforming Mars: Expédition Ares'),
    (23, 'es', 'Terraforming Mars: Expedición Ares'),
    (24, 'fr', 'Wingspan: Expansion Europeenne'),
    (24, 'es', 'Wingspan: Expansión Europea'),
    (25, 'fr', 'Spirit Island: Jagged Earth'),
    (25, 'es', 'Spirit Island: Jagged Earth'),
    (26, 'fr', 'Gloomhaven: Les Mâchoires du Lion'),
    (26, 'es', 'Gloomhaven: Las Fauces del León'),
    (27, 'fr', 'Codenames: Duet'),
    (27, 'es', 'Codenames: Dúo');
